### ISSUE TITLE
Object positions determining by robot direction

### ISSUE THREAD

**Issue by martinappo** [martinappo/robotiina2015#24]
- Realiseerisin juba roboti positsiooni saamise väravate järgi (RobotPosition.cpp). Viimati mingil määral töötas kuid peale koolis koodiga möllamist enam ei toimi. Niipalju, kui debugisin, siis updateFieldCoords meetodis (RobotPosition.cpp) yellowGate.getDistance() ja blueGate.getDistance() tagastasid koguaeg 10. (ilmselt mul lihtsalt kalibreerimata või see getDistance ei tööta hästi)
- Teiseks tuleks teha roboti suuna arvutamine väravate järgi ning siis ObjectPosition.cpp's sellega arvestada. Hetkel on updateCoordinates meetodis this->robotAngle = yellowGate.getAngle(); ehk annan lihtsalt kollase värava nurga tema vaatamis-suunaks, kuid kahjuks nii lihtne see pole. Ning ObjectPositionis kasutatakse siis seda robotAngle't getAngleToRobot meetodis, mis liidab objekti nurga roboti suhtes ja roboti vaatamis-suuna (ehk robotAngle) kokku. Ilmselt peaks selle kah üle mõtlema, mis teha kui nurk tuleb üle 360\* ja muud erijuhud. robotAngle peaks ilmselt ümber nimetama robotDirectioniks vms, et oleks asi selgem.

**Comment by GustavAmer** [comment]
- Roboti asukoht oleks kindlam tuletada väravate vahelise nurga:
  180 mod (yellowGate.getAngle() + blueGate.getAngle()) ja lühema külje järgi - vähendab kauguse kalibreerimisest tulenevat võimalikku viga.
- Roboti kindla asukoha kahest võimalikust ning sealt ka roboti suuna saab tuletada järgnevalt:
  - Meil on 2 väravat (R)ünnatav ja (K)aitstav värav. Kui liikudes päripäeva on nurk R->K väiksem kui K->R siis asub robot Kaitstavast väravast vaadates keskjoonest vasakul. Vastasel juhul paremal ning väärtuste võrdumisel keskjoonel.
  - Roboti suuna saab arvutada kasutades roboti asukohta ning nurka roboti nina(?) ja ühe värava vahel.
