### ISSUE TITLE
Ximea XiQ camera code integration

### ISSUE THREAD

**Issue by GustavAmer** [martinappo/robotiina2015#8]
Integrate code from https://github.com/lwd8cmd/pyXiQ with our project.

**Comment by GustavAmer** [comment]
The code is very Python oriented. Potentially useful methods seem to be taken from CMVision.

**Comment by andresviikmaa** [comment]
Try to get opencv demo running and then make it work with robotiina
http://www.ximea.com/support/wiki/vision-libraries/OpenCV
http://www.ximea.com/support/wiki/apis/XIMEA_API_Software_Package

**Comment by andresviikmaa** [comment]
Recompilation of OpenCV might be required 
http://www.ximea.com/support/wiki/vision-libraries/Opencv_howto_build

**Comment by GustavAmer** [comment]
Solved by: https://github.com/martinappo/robotiina2015/commit/c3aecefc2b577ae33ca4beff311ee0e2bd6dcb51
Required OpenCV API at: https://github.com/martinappo/robotiina2015/releases/tag/ximea
